### ISSUE TITLE
errors with "npm test"

### ISSUE THREAD

**Issue by jcw** [socketstream/socketstream-0.4#13]
After doing `npm install` on a clean checkout, `npm test` gives me the following errors on Mac OSX:

```
$ npm test

> socketstream-0.4@0.4.0experimental3 test /Users/jcw/Documents/Web/SourceCode/socketstream-0.4
> node_modules/.bin/mocha test


fs.js:684
  return binding.stat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory 'test.js'
    at Object.fs.statSync (fs.js:684:18)
    at lookupFiles (/Users/jcw/Documents/Web/SourceCode/socketstream-0.4/node_modules/mocha/bin/_mocha:380:17)
    at frames (/Users/jcw/Documents/Web/SourceCode/socketstream-0.4/node_modules/mocha/bin/_mocha:228:24)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/jcw/Documents/Web/SourceCode/socketstream-0.4/node_modules/mocha/bin/_mocha:227:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
$ 
```

Do I need to set up something else first?

**Comment by owenb** [comment]
Hi there

There are no tests for 0.4 yet. There were but I removed them as they were out of sync with the code.

As I continue to move stuff out into separate modules, most tests will be self contained within that module. I'm hoping the actual socketstream-0.4 module will contain very few lines of code and hence the only tests required will be a simple integration test.

Cheers,

Owen
