### ISSUE TITLE
browserify can't find dependencies

### ISSUE THREAD

**Issue by DeLaGuardo** [socketstream/socketstream-0.4#15]
```
module.js:340
    throw err;
    ^
Error: Cannot find module 'escodegen'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/delaguardo/MyProjects/socketstream-0.4/node_modules/browserify/node_modules/insert-module-globals/node_modules/lexical-scope/index.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

ugly fix is copy escodegen from

> **socketstream-0.4/node_modules/browserify/node_modules_/**

and put it to

> **socketstream-0.4/node_modules/browserify/node_modules/insert-module-globals/node_modules/lexical-scope/node_modules/**

**Comment by owenb** [comment]
Hey there

I remember reading of an issue in browserify which was solved recently. If you rm -fr your node_modules dir and reinstall it should fix it. Please close the issue if it does, if not I'll look into it more.

Cheers,

Owen

**Comment by DeLaGuardo** [comment]
Truly forgot that almost all dependency issues fix with magical **rm -rf node_modules && npm install**
